name: Update Ontivi Playlist
on:
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  workflow_dispatch:  # Ручной запуск

permissions:
  contents: write  # Разрешение на запись в репозиторий

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install system dependencies for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ca-certificates \
          fonts-liberation \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libc6 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgbm1 \
          libgcc1 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libstdc++6 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxss1 \
          libxtst6 \
          lsb-release \
          wget \
          xdg-utils
        
    - name: Run playlist builder
      run: node scripts/build_playlist.js
      env:
        NODE_ENV: production
        
    - name: Check for changes
      id: git-check
      run: |
        git config user.name "iptv-bot"
        git config user.email "bot@github.com"
        if git diff --quiet playlists/; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "✅ No changes detected in playlists"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "📦 Changes detected in playlists, preparing commit..."
          git status
        fi
      
    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git add playlists/
        git commit -m "Auto update: Ontivi IPTV playlist $(date '+%Y-%m-%d %H:%M')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '❌ Playlist update failed',
            body: `The Ontivi playlist update failed. Check the workflow run: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
          })
